server:
  host: "0.0.0.0"
  port: 50054

database:
  host: "postgres"
  port: 5432
  name: "uptimeping"
  user: "uptimeping"
  password: "uptimeping123"

logger:
  level: "info"
  format: "json"

environment: "dev"
