server:
  host: "0.0.0.0"
  port: 50053

database:
  host: "localhost"
  port: 5432
  name: "uptimeping"
  user: "uptimeping"
  password: "uptimeping"

logger:
  level: "info"
  format: "json"

environment: "dev"
