server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  positions_file: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__docker_container_name__']
        regex: '/(.*)'
        target_label: 'job'
      - source_labels: ['__path__']
        regex: '/var/lib/docker/containers/(.*?)/.*'
        target_label: 'id'
      - source_labels: ['__path__']
        regex: '(.*)'
        target_label: 'filename'
      - action: labelmap
        regex: '__meta_docker_container_label_([a-zA-Z0-9/_.-]+)'
      - source_labels: ['__meta_docker_container_image']
        target_label: image
      - source_labels: ['__meta_docker_container_name']
        target_label: container
      - action: replace
        source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
        replacement: '${1}'
      - action: replace
        source_labels: ['__meta_docker_container_id']
        target_label: id
        replacement: '${1}'
      - action: replace
        source_labels: ['__meta_docker_container_image']
        target_label: image
        replacement: '${1}'
      - action: replace
        source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
        replacement: '${1}'
      - action: replace
        source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: compose_project
        replacement: '${1}'