server:
  host: "0.0.0.0"
  port: 50052

database:
  host: "localhost"
  port: 5432
  name: "uptimeping"
  user: "uptimeping"
  password: "uptimeping123"
  ssl_mode: "disable"
  max_conns: 20
  min_conns: 5
  max_conn_life: "30m"
  max_conn_idle: "5m"
  health_check: "30s"
  max_retries: 3
  retry_interval: "1s"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"

logger:
  level: "info"
  format: "json"

environment: "dev"
