server:
  host: "0.0.0.0"
  port: 50057

database:
  host: "postgres"
  port: 5432
  name: "uptimeping"
  user: "uptimeping"
  password: "uptimeping123"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

logger:
  level: "info"
  format: "json"

environment: "dev"
